export default {
  port: 9000,
  host: "localhost",
  dbUrl: "mongodb://lmo:asdffdsa@localhost:27017/local-pos?authSource=admin",
  saltWorkFactor: 10,
  secretKey: "suuhh",
  page_limit: 50,
  mqttUrl: "ws://192.168.0.100:9001",
  mqttUserName: "detpos",
  mqttPassword: "asdffdsa",
  serverUrl: "http://detfsmm.com:9000",
  detailsaleCloudUrl: "http://detfsmm.com:9000/api/detail-sale",
  // coustomerCloudUrl: "http://detfsmm.com:9000/api/customer",
  coustomerCloudUrl: "http://detfsmm.com:9000/api/customer/local-create",
  debtCloudUrl: "http://detfsmm.com:9000/api/debt/local-create",
};
